name: ieee
channels:
- anaconda
- conda-forge
dependencies:
- python=3.8.5
- numpy
- pip:
    - absl-py==0.10.0
    - affine==2.3.0
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==20.2.0
    - backcall==0.2.0
    - bleach==3.2.1
    - blosc==1.8.3
    - branca==0.4.1
    - cachetools==4.1.1
    - certifi==2020.6.20
    - cffi==1.14.3
    - chardet==3.0.4
    - click==7.1.2
    - click-plugins==1.1.1
    - cligj==0.5.0
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - Cython==0.29.14
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - Fiona==1.8.13
    - findpeaks
    - gast==0.3.3
#    - GDAL==3.0.4
    - geojson==2.5.0
    - geopandas==0.6.2
    - google-auth==1.21.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.8
    - imageio==2.9.0
    - ipykernel==5.3.4
    - ipyleaflet==0.13.3
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - Jinja2==2.11.2
    - joblib==0.16.0
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - jupyterlab-pygments==0.1.1
    - Keras==2.3.1
    - Keras-Applications==1.0.8
    - Keras-Preprocessing==1.1.2
    - kiwisolver==1.2.0
    - Markdown==3.2.2
    - markdown2==2.3.9
    - MarkupSafe==1.1.1
    - matplotlib==3.3.2
    - mercantile==1.1.6
    - mistune==0.8.4
    - munch==2.5.0
    - nbclient==0.5.0
    - nbconvert==6.0.5
    - nbformat==5.0.7
    - nest-asyncio==1.4.0
    - networkx==2.4
    - notebook==6.1.4
#    - numpy==1.18.1
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.4
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - Pillow==7.0.0
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.7
    - protobuf==3.11.2
    - psutil==5.6.7
    - ptyprocess==0.6.0
    - pyarrow==0.17.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - Pygments==2.7.1
#    - pygobject==3.26.1
    - pyparsing==2.4.7
    - pyproj==2.4.2.post1
    - pyrsistent==0.17.3
#    - python-apt==1.6.5+ubuntu0.3
    - python-dateutil==2.8.1
    - pytz==2020.1
    - PyWavelets==1.1.1
    - PyYAML==5.3.1
    - pyzmq==19.0.2
    - rasterio==1.1.2
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-image==0.16.2
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - Send2Trash==1.5.0
    - Shapely==1.6.4.post2
    - six==1.15.0
    - snuggs==1.4.7
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - terminado==0.9.1
    - testpath==0.4.4
#    - torch==1.4.0+cpu
#    - torchvision==0.5.0+cpu
    - tornado==6.0.4
    - traitlets==4.3.3
    - traittypes==0.2.1
    - tqdm
    - urllib3==1.25.10
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - Werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xarray==0.14.1